# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         CGI-WebToolkit
version:      0.04
version_from: lib/CGI/WebToolkit.pm
installdirs:  site
requires:
    CGI:                           0
    CGI::Carp:                     0
    Data::Dump:                    0
    DBI:                           0
    Digest::MD5:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
